const root=document.getElementById('projectRoot');
const q=new URLSearchParams(location.search);
const safe=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const uniq=a=>[...new Set(a.filter(Boolean))];
function img(src,alt,cls=''){return `<img class="${cls}" src="${safe(src||'assets/placeholder.jpg')}" alt="${safe(alt)}" onerror="this.onerror=null;this.src='assets/placeholder.jpg'">`}
function video(src,title,cls=''){return `<video class="${cls}" src="${safe(src)}" controls autoplay muted loop playsinline preload="metadata" onerror="console.warn('Vídeo não encontrado:',this.src)">Seu navegador não suporta vídeo.</video>`}
function projectImages(p){const gallery=uniq(Array.isArray(p.gallery)?p.gallery:[]);if(gallery.length)return gallery;return uniq([p.cover,p.thumb])}
function relatedMedia(p){return p.thumb||p.cover||(p.gallery||[])[0]||'assets/placeholder.jpg'}
async function init(){try{const r=await fetch('portfolio.json');if(!r.ok)throw new Error('portfolio.json');const projects=await r.json();const project=projects.find(p=>p.id===q.get('id'))||projects[0];if(!project)throw new Error('Projeto não encontrado');document.title=`${project.titulo} — NOWHERE STUDIO`;render(project,projects);bindHeroParallax()}catch(e){console.error(e);root.innerHTML='<div class="loading">Não foi possível carregar este projeto.</div>'}}
function render(p,projects){
 const images=projectImages(p),hasVideo=Boolean(p.video),related=projects.filter(x=>x.id!==p.id&&x.categoria===p.categoria),fallbackRelated=related.length?related:projects.filter(x=>x.id!==p.id).slice(0,8);
 const heroSrc=p.cover||p.thumb||images[0]||'assets/placeholder.jpg';
 const conceptImage=p.concept||p.conceptImage||null;
 root.innerHTML=`
<section class="project-hero" id="projectHero"><div class="project-hero-bg" id="projectHeroBg">${img(heroSrc,'')}</div><div class="project-hero-overlay"></div><div class="project-hero-content"><div class="project-kicker">${safe(p.categoria||'Projeto')}</div><h1 class="project-title">${safe(p.titulo)}</h1></div></section>
<section class="project-details"><div class="project-meta"><div><span class="meta-label">Cliente</span><span class="meta-value">${safe(p.cliente||'—')}</span></div><div><span class="meta-label">Categoria</span><span class="meta-value">${safe(p.categoria||'—')}</span></div><div><span class="meta-label">Ano</span><span class="meta-value">${safe(p.ano||'—')}</span></div><div><p class="project-description">${safe(p.descricao||'')}</p></div></div></section>
<section class="project-showcase"><div class="showcase-head"><span class="mini">${hasVideo?'Projeto em movimento':'Projeto em destaque'}</span><h2>${hasVideo?'Visualização do projeto':'Galeria do projeto'}</h2></div>
${hasVideo?`<div class="video-showcase"><div class="video-main">${video(p.video,p.titulo)}</div></div>`:''}
${images.length?`<div class="showcase" id="showcase"><div class="showcase-main" id="showcaseMain"></div><div class="showcase-stack" id="showcaseStack"></div></div><p class="showcase-caption">Visualização automática <span>·</span> ${images.length} imagem${images.length!==1?'ns':''}</p>`:''}
${!hasVideo&&!images.length?`<div class="showcase-none">Este projeto ainda não possui mídia cadastrada.</div>`:''}
</section>
<section class="concept"><div class="concept-inner ${conceptImage?'':'no-concept-media'}">${conceptImage?`<div class="concept-media">${img(conceptImage,p.titulo)}</div>`:''}<div class="concept-copy"><h2>Conceito</h2><p>${safe(p.conceito||p.conceptText||p.descricao||'')}</p>${p.feedback?`<div class="feedback">“${safe(p.feedback)}”<br><strong>${safe(p.feedbackAutor||'')}</strong>${p.feedbackCargo?` · ${safe(p.feedbackCargo)}`:''}</div>`:''}</div></div></section>
<section class="related"><div class="related-head"><span class="mini">${safe(p.categoria||'Projetos')}</span><h2>Outros projetos</h2></div><div class="related-rail" id="relatedRail">${fallbackRelated.map(x=>`<a class="related-card" href="project.html?id=${encodeURIComponent(x.id)}">${img(relatedMedia(x),x.titulo)}<span>${safe(x.titulo)}</span></a>`).join('')}</div><p class="related-note">Projetos da mesma categoria passando automaticamente.</p></section>`;
 if(images.length)setupShowcase(images,p.titulo);
 setupRelatedRail();
}
function setupShowcase(images,title){const main=document.getElementById('showcaseMain'),stack=document.getElementById('showcaseStack');if(!main||!stack)return;let index=0;const draw=()=>{main.classList.add('changing');setTimeout(()=>{main.innerHTML=img(images[index],title);main.classList.remove('changing')},140);stack.innerHTML='';const sideCount=Math.min(3,Math.max(0,images.length-1));for(let i=1;i<=sideCount;i++){const src=images[(index+i)%images.length];stack.innerHTML+=`<div class="showcase-thumb incoming">${img(src,`${title} — visualização`)}</div>`}if(images.length===1)stack.classList.add('is-empty');else stack.classList.remove('is-empty')};draw();if(images.length>1)setInterval(()=>{index=(index+1)%images.length;draw()},4200)}
function setupRelatedRail(){const rail=document.getElementById('relatedRail');if(!rail||rail.children.length<2)return;const move=()=>{const card=rail.querySelector('.related-card');if(!card)return;const step=card.getBoundingClientRect().width+14;const end=rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-8;end?rail.scrollTo({left:0,behavior:'smooth'}):rail.scrollBy({left:step,behavior:'smooth'})};let timer=setInterval(move,4400);rail.addEventListener('mouseenter',()=>clearInterval(timer));rail.addEventListener('mouseleave',()=>{clearInterval(timer);timer=setInterval(move,4400)})}
function bindHeroParallax(){const hero=document.getElementById('projectHero'),bg=document.getElementById('projectHeroBg');if(!hero||!bg)return;hero.addEventListener('mousemove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;bg.style.transform=`scale(1.05) translate(${x*-12}px,${y*-9}px)`});hero.addEventListener('mouseleave',()=>bg.style.transform='scale(1.05)')}
document.getElementById('year').textContent=new Date().getFullYear();init();
