const $=(s,c=document)=>c.querySelector(s);const $$=(s,c=document)=>[...c.querySelectorAll(s)];
let projects=[];
const safe=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
async function initPortfolio(){try{const r=await fetch('portfolio.json');if(!r.ok)throw new Error('portfolio.json');projects=await r.json();hydrateStats();hydrateHero();renderFilters();renderProjects(projects);renderTestimonials();renderCarousel();}catch(e){$('#projectsGrid').innerHTML='<div class="loading">Não foi possível carregar portfolio.json.</div>';console.error(e)}}
function hydrateStats(){const cats=[...new Set(projects.map(p=>p.categoria).filter(Boolean))];const years=projects.map(p=>Number(p.ano)).filter(Number.isFinite).sort();$('#projectCount').textContent=projects.length;$('#categoryCount').textContent=cats.length;$('#yearRange').textContent=years.length?`${years[0]}–${years.at(-1)}`:'—'}
function imageOrFallback(img,path){img.src=path||'assets/placeholder.jpg';img.onerror=()=>{img.onerror=null;img.src='assets/placeholder.jpg'}}
function hydrateHero(){$$('[data-project-img]').forEach((img,i)=>imageOrFallback(img,projects[i]?.thumb||projects[i]?.cover))}
function renderFilters(){const cats=[...new Set(projects.map(p=>p.categoria).filter(Boolean))].sort();$('#filters').innerHTML=['Todos',...cats].map((c,i)=>`<button class="filter-btn ${i===0?'active':''}" data-cat="${safe(c)}">${safe(c)}</button>`).join('');$$('.filter-btn').forEach(b=>b.onclick=()=>{$$('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProjects(b.dataset.cat==='Todos'?projects:projects.filter(p=>p.categoria===b.dataset.cat))})}
function card(p){return `<article class="project-card" tabindex="0" role="link" data-id="${safe(p.id)}"><img loading="lazy" src="${safe(p.thumb||p.cover||'assets/placeholder.jpg')}" alt="${safe(p.titulo)}" onerror="this.onerror=null;this.src='assets/placeholder.jpg'"><div class="project-info"><h3>${safe(p.titulo)}</h3><p>${safe(p.categoria)} · ${safe(p.ano)}</p></div></article>`}
function renderProjects(list){$('#projectsGrid').innerHTML=list.map(card).join('');$$('.project-card').forEach(el=>{const go=()=>location.href=`project.html?id=${encodeURIComponent(el.dataset.id)}`;el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter')go()}})}
function renderTestimonials(){const q=projects.filter(p=>p.feedback&&p.feedbackAutor).slice(0,3);$('#testimonials').innerHTML=q.map(p=>`<article class="quote reveal"><p>“${safe(p.feedback)}”</p><small><strong>${safe(p.feedbackAutor)}</strong>${p.feedbackCargo?' · '+safe(p.feedbackCargo):''}</small></article>`).join('')||'<p>Nenhum feedback disponível.</p>';observeReveals()}
function renderCarousel(){const list=[...projects].sort((a,b)=>Number(b.ano)-Number(a.ano)).slice(0,8);$('#carousel').innerHTML=list.map(p=>`<a class="slide" href="project.html?id=${encodeURIComponent(p.id)}"><img src="${safe(p.cover||p.thumb||'assets/placeholder.jpg')}" alt="${safe(p.titulo)}" onerror="this.onerror=null;this.src='assets/placeholder.jpg'"><span>${safe(p.titulo)}</span></a>`).join('')}
$('#carNext').onclick=()=>$('#carousel').scrollBy({left:$('#carousel').clientWidth*.76,behavior:'smooth'});$('#carPrev').onclick=()=>$('#carousel').scrollBy({left:-$('#carousel').clientWidth*.76,behavior:'smooth'});
function parallax(){const stage=$('#parallaxStage');if(!stage)return;stage.addEventListener('mousemove',e=>{const r=stage.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$$('[data-depth]',stage).forEach(el=>{const d=Number(el.dataset.depth)||0;el.style.translate=`${x*d}px ${y*d}px`})});stage.addEventListener('mouseleave',()=>$$('[data-depth]',stage).forEach(el=>el.style.translate='0 0'))}
function observeReveals(){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&(e.target.classList.add('visible'),io.unobserve(e.target))),{threshold:.12});$$('.reveal:not(.visible)').forEach(el=>io.observe(el))}
document.addEventListener('DOMContentLoaded',()=>{$('#year').textContent=new Date().getFullYear();parallax();observeReveals();initPortfolio()});
