const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];let projects=[];
const safe=(v='')=>String(v).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const VIDEO_EXT=/\.(mp4|webm|ogg|mov)(?:$|[?#])/i;
const isVideo=src=>VIDEO_EXT.test(String(src||''));
const unique=a=>[...new Set(a.filter(Boolean))];
const galleryImages=p=>unique((Array.isArray(p.gallery)?p.gallery:[]).filter(src=>!isVideo(src)&&src!==p.thumb&&src!==p.cover));
const galleryVideos=p=>unique([...(Array.isArray(p.gallery)?p.gallery:[]),...(Array.isArray(p.videos)?p.videos:[]),...(p.video?[p.video]:[])].filter(isVideo));
const cardSource=p=>p.thumb||galleryImages(p)[0]||p.cover||'assets/placeholder.jpg';
async function initPortfolio(){try{const r=await fetch('portfolio.json');if(!r.ok)throw new Error('portfolio.json');projects=await r.json();hydrateStats();hydrateHero();renderFilters();renderTestimonials();renderCarousel()}catch(e){const grid=$('#projectsGrid');if(grid)grid.innerHTML='<div class="loading">Não foi possível carregar portfolio.json.</div>';console.error(e)}}
function hydrateStats(){const cats=[...new Set(projects.map(p=>p.categoria).filter(Boolean))],years=projects.map(p=>Number(p.ano)).filter(Number.isFinite).sort();$('#projectCount').textContent=projects.length;$('#categoryCount').textContent=cats.length;$('#yearRange').textContent=years.length?`${years[0]}–${years.at(-1)}`:'—'}
function imageOrFallback(img,path){img.src=path||'assets/placeholder.jpg';img.onerror=()=>{img.onerror=null;img.src='assets/placeholder.jpg'}}
function hydrateHero(){const hero=$('#heroImage');if(!hero)return;hero.src='assets/home-hero.jpg';hero.onerror=()=>{hero.onerror=null;const preferred=projects.find(p=>p.cover)||projects[0];imageOrFallback(hero,preferred?.cover||preferred?.thumb||galleryImages(preferred||{})[0])}}
function renderFilters(){const cats=[...new Set(projects.map(p=>p.categoria).filter(Boolean))].sort();if(!cats.length){renderProjects(projects);return}$('#filters').innerHTML=cats.map((c,i)=>`<button class="filter-btn ${i===0?'active':''}" data-cat="${safe(c)}">${safe(c)}</button>`).join('');const show=cat=>renderProjects(projects.filter(p=>p.categoria===cat));show(cats[0]);$$('.filter-btn').forEach(b=>b.onclick=()=>{$$('.filter-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');show(b.dataset.cat)})}
function card(p){const videos=galleryVideos(p);return `<article class="project-card" tabindex="0" role="link" data-id="${safe(p.id)}" data-video="${safe(videos[0]||'')}"><img loading="lazy" src="${safe(cardSource(p))}" alt="${safe(p.titulo)}" onerror="this.onerror=null;this.src='assets/placeholder.jpg'"><div class="project-info"><h3>${safe(p.titulo)}</h3><p>${safe(p.categoria)} · ${safe(p.ano)}</p></div></article>`}
function renderProjects(list){$('#projectsGrid').innerHTML=list.map(card).join('');$$('.project-card').forEach((el,i)=>{const p=list[i],go=()=>location.href=`project.html?id=${encodeURIComponent(el.dataset.id)}`;el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter')go()};if(!p.thumb)setupImagePreview(el,galleryImages(p));setupVideoPreview(el);setTimeout(()=>el.classList.add('visible'),80+i*85)})}
function setupImagePreview(el,images){if(!images||images.length<2)return;const img=$('img',el);let timer=null,index=0;const stop=()=>{clearInterval(timer);timer=null;index=0;img.src=images[0]};const start=()=>{if(timer)return;timer=setInterval(()=>{index=(index+1)%images.length;img.style.opacity='.35';setTimeout(()=>{img.src=images[index];img.style.opacity='1'},120)},900)};el.addEventListener('mouseenter',start);el.addEventListener('mouseleave',stop);el.addEventListener('focus',start);el.addEventListener('blur',stop)}
function setupVideoPreview(el){const src=el.dataset.video;if(!src)return;let delay,timer,videoEl;const img=$('img',el);const stop=()=>{clearTimeout(delay);clearTimeout(timer);if(videoEl){videoEl.pause();videoEl.remove();videoEl=null}img.style.display='block'};const start=()=>{delay=setTimeout(()=>{videoEl=document.createElement('video');videoEl.src=src;videoEl.muted=true;videoEl.autoplay=true;videoEl.playsInline=true;videoEl.preload='metadata';videoEl.style.cssText='position:absolute;inset:0;width:100%;height:100%;object-fit:cover;z-index:1';videoEl.onloadeddata=()=>videoEl.play().catch(()=>{});videoEl.onerror=()=>stop();el.insertBefore(videoEl,img.nextSibling);img.style.display='none';timer=setTimeout(stop,3000)},650)};el.addEventListener('mouseenter',start);el.addEventListener('mouseleave',stop);el.addEventListener('focus',start);el.addEventListener('blur',stop)}
function renderTestimonials(){const q=projects.filter(p=>p.feedback&&p.feedbackAutor).slice(0,3);$('#testimonials').innerHTML=q.map(p=>`<article class="quote reveal"><p>“${safe(p.feedback)}”</p><small><strong>${safe(p.feedbackAutor)}</strong>${p.feedbackCargo?' · '+safe(p.feedbackCargo):''}</small></article>`).join('')||'<p>Nenhum feedback disponível.</p>';observeReveals()}
function renderCarousel(){const list=[...projects].sort((a,b)=>Number(b.ano)-Number(a.ano)).slice(0,10),carousel=$('#carousel');if(!carousel)return;const slides=list.map(p=>`<a class="slide" href="project.html?id=${encodeURIComponent(p.id)}"><img loading="lazy" src="${safe(cardSource(p))}" alt="${safe(p.titulo)}" onerror="this.onerror=null;this.src='assets/placeholder.jpg'"><span>${safe(p.titulo)}</span></a>`).join('');carousel.innerHTML=slides+slides;let paused=false,raf=null,last=0;const half=()=>carousel.scrollWidth/2;const tick=t=>{if(!last)last=t;const delta=Math.min(40,t-last);last=t;if(!paused&&carousel.scrollWidth>carousel.clientWidth){carousel.scrollLeft+=delta*.035;if(carousel.scrollLeft>=half()-2)carousel.scrollLeft=0}raf=requestAnimationFrame(tick)};carousel.addEventListener('mouseenter',()=>paused=true);carousel.addEventListener('mouseleave',()=>paused=false);carousel.addEventListener('focusin',()=>paused=true);carousel.addEventListener('focusout',()=>paused=false);requestAnimationFrame(tick)}
function heroParallax(){const hero=$('#hero'),bg=$('#heroBackground');if(!hero||!bg)return;hero.addEventListener('mousemove',e=>{const r=hero.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;bg.style.transform=`scale(1.05) translate(${x*-14}px,${y*-10}px)`});hero.addEventListener('mouseleave',()=>bg.style.transform='scale(1.05) translate(0,0)')}
function observeReveals(){const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&(e.target.classList.add('visible'),io.unobserve(e.target))),{threshold:.12});$$('.reveal:not(.visible)').forEach(el=>io.observe(el))}
document.addEventListener('DOMContentLoaded',()=>{$('#year').textContent=new Date().getFullYear();heroParallax();observeReveals();initPortfolio()});
